### ISSUE TITLE
Analysis triggered when moving cursor to different line

### ISSUE THREAD

**Issue by jalgaba** [dario-valles/vscode-phpstan-larastan#2]
First of all, thank you for creating and maintaining this extension, it works really well.

I noticed that an analysis is triggered by simply moving the cursor to a different line, is this by design?
Since nothing in the file can change by moving the cursor around, it's seems like a waste of resources.

https://user-images.githubusercontent.com/9779631/139760043-bc24668a-0a97-43fc-8b45-2473c50fa36f.mp4

Using v1.0.5
vscode 1.61.2

**Comment by dario-valles** [comment]
I'll check this, thanks for the feedback
